In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
students = pd.read_csv("students.csv")
students

     Name  Age  Maths  Science  English
0    Aman   19     85       90       80
1    Riya   20     95       89       94
2   Karan   18     76       82       78
3    Neha   21     91       93       88
4  Vikram   19     88       85       90
5  Anjali   20     97       95       92

In [4]:
students.describe()

             Age      Maths    Science    English
count   6.000000   6.000000   6.000000   6.000000
mean   19.500000  88.666667  89.000000  87.000000
std     1.048809   7.607014   4.857983   6.542171
min    18.000000  76.000000  82.000000  78.000000
25%    19.000000  85.750000  86.000000  82.000000
50%    19.500000  89.500000  89.500000  89.000000
75%    20.000000  94.000000  92.250000  91.500000
max    21.000000  97.000000  95.000000  94.000000

In [ ]:
sorted_students = students.sort_values(
    by="Maths",
    ascending=False
)

sorted_students